import mysql.connector as mysql
con = mysql.connect(host='localhost',user='root',password='root',database='sedb')
cur = con.cursor()
query = input('Enter Query : ')
id = int(input('Enter Id   : '))
name = input('Enter Name   : ')
sal = int(input('Enter Salary  :'))
cur.execute(query,(name,sal,id))
cur.close()
con.commit()
