li = list()
print(li)
li.insert(0,10)
li.insert(1,34)
li.insert(2,70)
li.append(98)
li.append(90)
li.append(100)
print(li)
print(li.__len__())
print(li.__sizeof__())
print(f'Deleted element is : {li.pop()}')
li.clear()
print(li)
print(li.__sizeof__())